// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwmzggzjfahapykbtnmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bXpnZ3pqZmFoYXB5a2J0bm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTMzNTksImV4cCI6MjA3MTI2OTM1OX0.NksXeKPtxGWgwdzOGNLG6gJab2If0FSMdt5PuYJu6e4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});